# Configuracion de Producción - Brosteria CRM
# Este perfil se activa con la variable de entorno SPRING_PROFILES_ACTIVE=prod

# Base de Datos
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Desactivar documentacion publica de Swagger/SpringDoc para evitar Ingenieria Inversa
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Logs y Depuracion
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

# Correo SMTP (Producción)
spring.mail.properties.mail.debug=false
