spring.application.name=BrosteriaCRM
server.port=8081

# Base de Datos apuntando al Pooler de Supabase (Evita UnknownHostException)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.htetwptrtgcwhhpgjfvl
spring.datasource.password=#16j0sUBV_supabase
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicialización automática con data.sql
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Configuración de Seguridad JWT
jwt.secret=M1_CL4V3_S3CR3T4_M0Y_L4RG4_Y_S3GUR4_P4R4_3L_PR0Y3CT0_BROSTERIA_CRM_2026
jwt.expiration=86400000

# Configuración SMTP de Gmail (Ajustar credenciales de producción)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=josuebecerrav19@gmail.com
spring.mail.password=myikgpjkczmcswwp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2